skip_non_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python35"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python37"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python38"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python35-x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python36-x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python37-x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python38-x64"

install:
  - ps: |
      if ($IsWindows -and (-not (Test-Path $env:PYTHON))) {
        curl -o install_python.ps1 https://raw.githubusercontent.com/matthew-brett/multibuild/11a389d78892cf90addac8f69433d5e22bfa422a/install_python.ps1
        .\install_python.ps1
      }
  - cmd: set PATH=%PYTHON%;%PATH%
  - cmd: "%PYTHON%\\python.exe -m pip install wheel scikit-build ninja"

build: off

test_script:
  - cmd: "%PYTHON%\\python.exe setup.py bdist_wheel"
  - sh: docker run --rm -v $(pwd):/io quay.io/pypa/manylinux1_x86_64 /bin/bash /io/build_wheels.sh

artifacts:
  - path: dist\*

deploy:
  description: elkai appveyor wheels
  provider: GitHub
  auth_token:
    secure: rdTufwRoahOQ+IUaB7OgWdL2U2VO0I40kjKxiN8iaacMzxhn/sBx72TIOIf3GWAf

